name: docker-hub

on:
  push:
    tags:
      - 'v*'

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/expensetrace:latest,${{ vars.DOCKERHUB_USERNAME }}/expensetrace:${{ github.ref_name }}
  
  docker-hub-description:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Update docker hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: GustavoCaso/expensetrace
